version: "3"

services:
  jugspeed_database:
    image: postgres
    container_name: jugspeed_Database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - jugspeed_database_volume:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    restart: always

  jugspeed_pgadmin:
      image: dpage/pgadmin4
      container_name: jugspeed_Admin
      depends_on:
        - jugspeed_database
      ports:
        - "8080:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: cms@email.com
        PGADMIN_DEFAULT_PASSWORD: cms
      restart: always

volumes: 
  jugspeed_database_volume:
    name: jugspeed_database_volume